### ISSUE TITLE
Zobrazení RPM v seznamu parametrů UAV

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/qgroundcontrol#2]
Nyní QGC (upsteam/master) umí parserovat mavlink RAW_RPM (z rpm uOrb zprávy) data a vizualizovat je v podobě hodnoty nebo grafu v mavlink analyzátoru. Nyní je potřeba tuto hodnotu dostat do seznamu zobrazovaných hodnot z UAV. 

Vidím pak možná problém tuto věc dostat do upstreamu, protože moc lidí nemá RPM senzor/zprávy.

**Comment by kaklik** [comment]
Tohle je aktuálně myslím dostatečně vyřešeno použitím terminálu.
